name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: |
        cd backend && pnpm install
        cd ../frontend && pnpm install
    
    - name: Run backend tests
      run: |
        cd backend
        pnpm run test
    
    - name: Build backend
      run: |
        cd backend
        pnpm run build
    
    - name: Build frontend
      run: |
        cd frontend
        pnpm run build
    
    - name: Lint backend
      run: |
        cd backend
        pnpm run lint
    
    - name: Lint frontend
      run: |
        cd frontend
        pnpm run lint

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy Backend to Render
      uses: johnbeynon/render-deploy@v1
      with:
        service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy Frontend to Render
      uses: johnbeynon/render-deploy@v1
      with:
        service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-success: true 